---@class Weapon
---@field name string
---@field label string
---@field weapontype string
---@field ammotype? string
---@field damagereason string


---@deprecated This file is deprecated and will be removed in the future. If you are utilizing QB-Core bridge functionality you will need to populate weapons here for them to be available in QBCore.Shared.Weapons. If not please add your weapons in ox_inventory/data/weapons.lua file. Currently weapons in this file will be converted on next server start.
---@type table<number, Weapon>
return {
	-- // WEAPONS
	-- Melee
	[`weapon_unarmed`] 				 = {name = 'weapon_unarmed', 		label = 'Poings', 				weapontype = 'Melee',	ammotype = nil, damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_dagger`] 				 = {name = 'weapon_dagger', 		label = 'Dague', 				weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_bat`] 					 = {name = 'weapon_bat', 			label = 'Batte', 				weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_bottle`] 				 = {name = 'weapon_bottle', 		label = 'Bouteille cassée', 	weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_crowbar`] 				 = {name = 'weapon_crowbar', 		label = 'Pied-de-biche', 		weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_flashlight`] 			 = {name = 'weapon_flashlight', 	label = 'Lampe torche', 		weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_golfclub`] 			 = {name = 'weapon_golfclub', 		label = 'Club de golf', 		weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_hammer`] 				 = {name = 'weapon_hammer', 		label = 'Marteau', 				weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_hatchet`] 				 = {name = 'weapon_hatchet', 		label = 'Hachette', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_knuckle`] 				 = {name = 'weapon_knuckle', 		label = 'Poing américain', 		weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_knife`] 				 = {name = 'weapon_knife', 			label = 'Couteau', 				weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_machete`] 				 = {name = 'weapon_machete', 		label = 'Machette', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_switchblade`] 			 = {name = 'weapon_switchblade', 	label = 'Couteau à cran d\'arrêt', weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_nightstick`] 			 = {name = 'weapon_nightstick', 	label = 'Matraque', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_wrench`] 				 = {name = 'weapon_wrench', 		label = 'Clé', 					weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_battleaxe`] 			 = {name = 'weapon_battleaxe', 		label = 'Hache de combat', 		weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
	[`weapon_poolcue`] 				 = {name = 'weapon_poolcue', 		label = 'Queue de billard', 	weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_briefcase`] 			 = {name = 'weapon_briefcase', 		label = 'Mallette', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_briefcase_02`] 		 = {name = 'weapon_briefcase_02', 	label = 'Mallette', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_garbagebag`] 			 = {name = 'weapon_garbagebag', 	label = 'Sac poubelle', 		weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_handcuffs`] 			 = {name = 'weapon_handcuffs', 		label = 'Menottes', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_bread`] 				 = {name = 'weapon_bread', 			label = 'Baguette', 			weapontype = 'Melee',	ammotype = nil,	damagereason = 'Tué à mains nues / Frappé / Exécuté / Battu / Assassiné / Battu à mort'},
	[`weapon_stone_hatchet`] 		 = {name = 'weapon_stone_hatchet', 	label = 'Hachette en pierre', 	weapontype = 'Melee',	ammotype = nil,	damagereason = 'Poignardé / Stabbed / Éviscéré'},
    -- Pistolets
	[`weapon_pistol`] 				 = {name = 'weapon_pistol', 		label = 'Pistolet', 				weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_pistol_mk2`] 			 = {name = 'weapon_pistol_mk2', 	label = 'Pistolet Mk2', 			weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_combatpistol`] 		 = {name = 'weapon_combatpistol', 	label = 'Pistolet de combat', 		weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_appistol`] 			 = {name = 'weapon_appistol', 		label = 'Pistolet AP', 				weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_stungun`] 				 = {name = 'weapon_stungun', 		label = 'Taser', 					weapontype = 'Pistol',	ammotype = 'AMMO_STUNGUN',	damagereason = 'Mort'},
	[`weapon_pistol50`] 			 = {name = 'weapon_pistol50', 		label = 'Pistolet Cal .50', 		weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_snspistol`] 			 = {name = 'weapon_snspistol', 		label = 'Pistolet SNS', 			weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_snspistol_mk2`] 	     = {name = 'weapon_snspistol_mk2', 	label = 'Pistolet SNS Mk2', 		weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',   damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_heavypistol`] 			 = {name = 'weapon_heavypistol', 	label = 'Pistolet lourd', 			weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_vintagepistol`] 		 = {name = 'weapon_vintagepistol', 	label = 'Pistolet vintage', 		weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_flaregun`] 			 = {name = 'weapon_flaregun', 		label = 'Pistolet de détresse', 	weapontype = 'Pistol',	ammotype = 'AMMO_FLARE',	damagereason = 'Mort'},
	[`weapon_marksmanpistol`] 		 = {name = 'weapon_marksmanpistol', label = 'Pistolet de précision', 	weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_revolver`] 			 = {name = 'weapon_revolver', 		label = 'Revolver', 				weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_revolver_mk2`] 		 = {name = 'weapon_revolver_mk2', 	label = 'Revolver Mk2', 			weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_doubleaction`] 	     = {name = 'weapon_doubleaction', 	label = 'Revolver à double action', weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_raypistol`]			 = {name = 'weapon_raypistol',		label = 'Pistolet rayon',			weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_ceramicpistol`]		 = {name = 'weapon_ceramicpistol', 	label = 'Pistolet en céramique',	weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_navyrevolver`]        	 = {name = 'weapon_navyrevolver', 	label = 'Revolver de la marine',	weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_gadgetpistol`] 		 = {name = 'weapon_gadgetpistol', 	label = 'Pistolet gadget',			weapontype = 'Pistol',	ammotype = 'AMMO_PISTOL',	damagereason = 'Tiré avec un pistolet / Blasté / Bouché / Tiré'},
	[`weapon_stungun_mp`] 			 = {name = 'weapon_stungun_mp', 	label = 'Taser', 					weapontype = 'Pistol',	ammotype = 'AMMO_STUNGUN',	damagereason = 'Mort'},
    -- Mitraillettes
	[`weapon_microsmg`] 			 = {name = 'weapon_microsmg', 		label = 'Micro SMG', 			weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_smg`] 				 	 = {name = 'weapon_smg', 			label = 'SMG', 					weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_smg_mk2`] 				 = {name = 'weapon_smg_mk2', 		label = 'SMG MK2', 			    weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_assaultsmg`] 			 = {name = 'weapon_assaultsmg', 	label = 'SMG d\'assaut', 		weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_combatpdw`] 			 = {name = 'weapon_combatpdw', 		label = 'PDW de combat', 		weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_machinepistol`] 		 = {name = 'weapon_machinepistol', 	label = 'Pistolet mitrailleur',	weapontype = 'Submachine Gun',	ammotype = 'AMMO_PISTOL',	damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_minismg`] 				 = {name = 'weapon_minismg', 		label = 'Mini SMG', 			weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
	[`weapon_raycarbine`]	         = {name = 'weapon_raycarbine', 	label = 'Carabine à rayons',	weapontype = 'Submachine Gun',	ammotype = 'AMMO_SMG',		damagereason = 'Criblé de balles / Percé / Achevé / Mitraillette'},
    -- Fusils à pompe
	[`weapon_pumpshotgun`] 			 = {name = 'weapon_pumpshotgun', 	 	label = 'Fusil à pompe', 				weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_pumpshotgun_mk2`]		 = {name = 'weapon_pumpshotgun_mk2',	label = 'Fusil à pompe MK2', 			weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_sawnoffshotgun`] 		 = {name = 'weapon_sawnoffshotgun', 	label = 'Fusil à canon scié', 			weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_assaultshotgun`] 		 = {name = 'weapon_assaultshotgun', 	label = 'Fusil à pompe d\'assaut', 		weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_bullpupshotgun`] 		 = {name = 'weapon_bullpupshotgun', 	label = 'Fusil à pompe Bullpup', 		weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_musket`] 			     = {name = 'weapon_musket', 			label = 'Mousquet', 						weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_heavyshotgun`] 		 = {name = 'weapon_heavyshotgun', 	 	label = 'Fusil à pompe lourd', 			weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_dbshotgun`] 			 = {name = 'weapon_dbshotgun', 		 	label = 'Fusil à pompe à double canon', 	weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_autoshotgun`] 			 = {name = 'weapon_autoshotgun', 	 	label = 'Fusil à pompe automatique', 		weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
	[`weapon_combatshotgun`]		 = {name = 'weapon_combatshotgun', 		label = 'Fusil à pompe de combat',		weapontype = 'Shotgun',	ammotype = 'AMMO_SHOTGUN',	damagereason = 'Dévasté / Pulvérisé / Fusillé avec un fusil à pompe'},
    -- Fusils d'assaut
	[`weapon_assaultrifle`] 		 = {name = 'weapon_assaultrifle', 	 	label = 'Fusil d\'assaut', 					weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_assaultrifle_mk2`] 	 = {name = 'weapon_assaultrifle_mk2', 	label = 'Fusil d\'assaut MK2', 				weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_carbinerifle`] 		 = {name = 'weapon_carbinerifle', 	 	label = 'Carabine', 						weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_carbinerifle_mk2`] 	 = {name = 'weapon_carbinerifle_mk2', 	label = 'Carabine MK2', 					weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_advancedrifle`] 		 = {name = 'weapon_advancedrifle', 	 	label = 'Fusil avancé', 					weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_specialcarbine`] 		 = {name = 'weapon_specialcarbine', 	label = 'Carabine spéciale', 				weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_specialcarbine_mk2`]	 = {name = 'weapon_specialcarbine_mk2',	label = 'Carabine spéciale MK2',	        weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_bullpuprifle`] 		 = {name = 'weapon_bullpuprifle', 	 	label = 'Fusil Bullpup', 					weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_bullpuprifle_mk2`]		 = {name = 'weapon_bullpuprifle_mk2', 	label = 'Fusil Bullpup MK2',				weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_compactrifle`] 		 = {name = 'weapon_compactrifle', 	 	label = 'Fusil compact', 					weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_militaryrifle`]		 = {name = 'weapon_militaryrifle', 		label = 'Fusil militaire',   				weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_heavyrifle`] 			 = {name = 'weapon_heavyrifle', 	 	label = 'Fusil lourd', 						weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
	[`weapon_tacticalrifle`] 		 = {name = 'weapon_tacticalrifle', 	 	label = 'Fusil de service', 				weapontype = 'Assault Rifle',	ammotype = 'AMMO_RIFLE',	damagereason = 'Terminé / Fusillé / Abattu / Mis à terre'},
    -- Mitrailleuses légères
	[`weapon_mg`] 					 = {name = 'weapon_mg', 			label = 'Mitrailleuse', 				weapontype = 'Light Machine Gun',	ammotype = 'AMMO_MG',	damagereason = 'Mitrailleuse / Arrosé / Ruiné'},
	[`weapon_combatmg`] 			 = {name = 'weapon_combatmg', 		label = 'MG de combat', 				weapontype = 'Light Machine Gun',	ammotype = 'AMMO_MG',	damagereason = 'Mitrailleuse / Arrosé / Ruiné'},
	[`weapon_combatmg_mk2`]	 		 = {name = 'weapon_combatmg_mk2', 	label = 'MG de combat MK2',			weapontype = 'Light Machine Gun',	ammotype = 'AMMO_MG',	damagereason = 'Mitrailleuse / Arrosé / Ruiné'},
	[`weapon_gusenberg`] 			 = {name = 'weapon_gusenberg', 		label = 'SMG Thompson', 				weapontype = 'Light Machine Gun',	ammotype = 'AMMO_MG',	damagereason = 'Mitrailleuse / Arrosé / Ruiné'},
    -- Fusils de sniper
	[`weapon_sniperrifle`] 			 = {name = 'weapon_sniperrifle', 	 	label = 'Fusil de sniper', 				weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER',			damagereason = 'Snipé / Éliminé à distance / Visé'},
	[`weapon_heavysniper`] 			 = {name = 'weapon_heavysniper', 	 	label = 'Fusil de sniper lourd', 		weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER',			damagereason = 'Snipé / Éliminé à distance / Visé'},
	[`weapon_heavysniper_mk2`]		 = {name = 'weapon_heavysniper_mk2', 	label = 'Fusil de sniper lourd MK2',	weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER',			damagereason = 'Snipé / Éliminé à distance / Visé'},
	[`weapon_marksmanrifle`] 		 = {name = 'weapon_marksmanrifle', 	 	label = 'Fusil tireur d\'élite', 			weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER',			damagereason = 'Snipé / Éliminé à distance / Visé'},
	[`weapon_marksmanrifle_mk2`]	 = {name = 'weapon_marksmanrifle_mk2',	label = 'Fusil tireur d\'élite MK2',	    weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER',			damagereason = 'Snipé / Éliminé à distance / Visé'},
	[`weapon_remotesniper`] 		 = {name = 'weapon_remotesniper', 	 	label = 'Fusil de sniper à distance',	weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER_REMOTE',	damagereason = 'Snipé / Éliminé à distance / Visé'},
	[`weapon_precisionrifle`] 		 = {name = 'weapon_precisionrifle', 	label = 'Fusil de précision', 			weapontype = 'Sniper Rifle',	ammotype = 'AMMO_SNIPER',	        damagereason = 'Snipé / Éliminé à distance / Visé'},
    -- Armes lourdes
	[`weapon_rpg`] 					 = {name = 'weapon_rpg', 			    label = 'RPG', 						weapontype = 'Heavy Weapons',	ammotype = 'AMMO_RPG',				damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_grenadelauncher`] 		 = {name = 'weapon_grenadelauncher', 	label = 'Lance-grenades', 			weapontype = 'Heavy Weapons',	ammotype = 'AMMO_GRENADELAUNCHER',	damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_grenadelauncher_smoke`] = {name = 'weapon_grenadelauncher_smoke', label = 'Lance-grenades fumigène', weapontype = 'Heavy Weapons',	ammotype = 'AMMO_GRENADELAUNCHER',	damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_minigun`] 				 = {name = 'weapon_minigun', 			label = 'Minigun', 					weapontype = 'Heavy Weapons',	ammotype = 'AMMO_MINIGUN',			damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_firework`] 			 = {name = 'weapon_firework', 		    label = 'Lanceur de feux d\'artifice', weapontype = 'Heavy Weapons',	ammotype = nil,						damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_railgun`] 				 = {name = 'weapon_railgun', 		    label = 'Canon électromagnétique', 	weapontype = 'Heavy Weapons',	ammotype = nil,						damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_hominglauncher`] 		 = {name = 'weapon_hominglauncher', 	    label = 'Lanceur à tête chercheuse', 	weapontype = 'Heavy Weapons',	ammotype = 'AMMO_STINGER',			damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_compactlauncher`] 		 = {name = 'weapon_compactlauncher',     label = 'Lanceur compact', 			weapontype = 'Heavy Weapons',	ammotype = nil,						damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_rayminigun`]			 = {name = 'weapon_rayminigun', 	    label = 'Minigun à rayon',		    weapontype = 'Heavy Weapons',	ammotype = 'AMMO_MINIGUN',			damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_emplauncher`] 			 = {name = 'weapon_emplauncher', 	    label = 'Lanceur EMP', 				weapontype = 'Heavy Weapons',	ammotype = 'AMMO_EMPLAUNCHER',		damagereason = 'Mort'},
    -- Objets lançables
	[`weapon_grenade`] 		        = {name = 'weapon_grenade', 		label = 'Grenade', 			weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Bombardé / Explosé / Détaché / Fait sauter'},
	[`weapon_bzgas`] 		        = {name = 'weapon_bzgas', 			label = 'Gaz BZ', 			weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Mort'},
	[`weapon_molotov`] 		        = {name = 'weapon_molotov', 		label = 'Cocktail Molotov', 			weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Brûlé / Flambé / Barbecue'},
	[`weapon_stickybomb`] 	        = {name = 'weapon_stickybomb', 	    label = 'Bombe collante', 				weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Bombardé / Explosé / Détaché / Fait sauter'},
	[`weapon_proxmine`] 	        = {name = 'weapon_proxmine', 		label = 'Grenade de proximité', weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Bombardé / Explosé / Détaché / Fait sauter'},
	[`weapon_snowball`] 	        = {name = 'weapon_snowball', 		label = 'Boule de neige', 		weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Mort'},
	[`weapon_pipebomb`] 	        = {name = 'weapon_pipebomb', 		label = 'Bombe tuyau', 		weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Bombardé / Explosé / Détaché / Fait sauter'},
	[`weapon_ball`] 		        = {name = 'weapon_ball', 			label = 'Balle', 			weapontype = 'Throwable',	ammotype = 'AMMO_BALL',		damagereason = 'Mort'},
	[`weapon_smokegrenade`]         = {name = 'weapon_smokegrenade', 	label = 'Grenade fumigène', 	weapontype = 'Throwable',	ammotype = nil,				damagereason = 'Mort'},
	[`weapon_flare`] 		        = {name = 'weapon_flare', 			label = 'Fusée éclairante', 	weapontype = 'Throwable',	ammotype = 'AMMO_FLARE',	damagereason = 'Mort'},
    -- Divers
	[`weapon_petrolcan`] 			= {name = 'weapon_petrolcan', 			label = 'Bidon d\'essence', 				weapontype = 'Miscellaneous',	ammotype = 'AMMO_PETROLCAN',		damagereason = 'Mort'},
	[`gadget_parachute`] 			= {name = 'gadget_parachute', 			label = 'Parachute', 					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Mort'},
	[`weapon_fireextinguisher`] 	= {name = 'weapon_fireextinguisher',	label = 'Extincteur',					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Mort'},
	[`weapon_hazardcan`]			= {name = 'weapon_hazardcan',			label = 'Bidon de danger',			    weapontype = 'Miscellaneous',	ammotype = 'AMMO_PETROLCAN',		damagereason = 'Mort'},
	[`weapon_fertilizercan`]		= {name = 'weapon_fertilizercan',		label = 'Bidon d\'engrais',				weapontype = 'Miscellaneous',	ammotype = 'AMMO_FERTILIZERCAN',	damagereason = 'Mort'},
	[`weapon_barbed_wire`]			= {name = 'weapon_barbed_wire',			label = 'Fil barbelé',					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Piqué'},
	[`weapon_drowning`]				= {name = 'weapon_drowning',			label = 'Noyade',						weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Mort'},
	[`weapon_drowning_in_vehicle`]	= {name = 'weapon_drowning_in_vehicle',	label = 'Noyade dans un véhicule',		weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Mort'},
	[`weapon_bleeding`]				= {name = 'weapon_bleeding',			label = 'Saignement',					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Saigné à mort'},
	[`weapon_electric_fence`]		= {name = 'weapon_electric_fence',		label = 'Clôture électrique',			weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Frit'},
	[`weapon_explosion`]			= {name = 'weapon_explosion',			label = 'Explosion',					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Annihilé'},
	[`weapon_fall`]					= {name = 'weapon_fall',				label = 'Chute',						weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Suicide'},
	[`weapon_exhaustion`]			= {name = 'weapon_exhaustion',			label = 'Épuisement',					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Mort'},
	[`weapon_hit_by_water_cannon`]	= {name = 'weapon_hit_by_water_cannon',	label = 'Canon à eau',					weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Mort'},
	[`weapon_rammed_by_car`]		= {name = 'weapon_rammed_by_car',		label = 'Écrasé - Véhicule',			weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Écrasé / Renversé / Fauché'},
	[`weapon_run_over_by_car`]		= {name = 'weapon_run_over_by_car',		label = 'Passé sur - Véhicule',			weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Écrasé / Renversé / Fauché'},
	[`weapon_heli_crash`]			= {name = 'weapon_heli_crash',			label = 'Crash d\'hélicoptère',			weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Crash d\'hélicoptère'},
	[`weapon_fire`]					= {name = 'weapon_fire',				label = 'Feu',							weapontype = 'Miscellaneous',	ammotype = nil,						damagereason = 'Brûlé / Flambé / Barbecue'},
	[`weapon_metaldetector`] 		= {name = 'weapon_metaldetector', 	    label = 'Détecteur de métaux', 	        weapontype = 'Miscellaneous',	ammotype = nil,	                	damagereason = 'Mort'},
	-- Animaux
	[`weapon_animal`]               = {name = 'weapon_animal',	label = 'Animal',				weapontype = 'Animals',	ammotype = nil,	damagereason = 'Mutilé'},
	[`weapon_cougar`]               = {name = 'weapon_cougar',	label = 'Cougar',				weapontype = 'Animals',	ammotype = nil,	damagereason = 'Mutilé'},
}
